import type {
  CommoditySensitivity as MarketCommoditySensitivity,
  Company,
  CompanySize,
  Country,
  Currency,
  Exchange,
  Relation,
  Sector,
} from './market'

export type CompanyScale = CompanySize
export type PrimaryCountry = Country
export type PrimaryCurrency = Currency
export type PrimaryExchange = Exchange | 'TSE Prime' | 'TSE Standard' | 'TSE Growth'

export type RelationKind =
  | 'supplier'
  | 'customer'
  | 'rival'
  | 'platform'
  | 'financing'
  | 'logistics'
  | 'fxProxy'
  | 'commodityProxy'
  | 'policy'

export type RelationSignal = 'positive' | 'negative' | 'mixed'
export type FxPair = 'USD/KRW' | 'JPY/KRW' | 'USD/JPY'

export type Commodity =
  | 'memory'
  | 'cloudGpu'
  | 'lithium'
  | 'nickel'
  | 'copper'
  | 'steel'
  | 'lng'
  | 'oil'
  | 'uranium'
  | 'rareEarth'
  | 'biotechFunding'
  | 'adSpending'

export interface RelationSeed extends Relation {
  kind: RelationKind
  signal: RelationSignal
}

export interface FxSensitivitySeed {
  pair: FxPair
  weight: number
  reason: string
}

export interface CommoditySensitivitySeed {
  commodity: Commodity
  weight: number
  reason: string
}

export interface CompanyBlueprint {
  ticker: string
  name: string
  size: CompanyScale
  sector: Sector
  tags?: string[]
  description: string
  basePrice: number
  shares: number
  beta: number
  revenue: number
  margin: number
  backlog: number
  debtRatio: number
  quality: number
  dividendYield: number
  primaryCountry: PrimaryCountry
  primaryCurrency: PrimaryCurrency
  primaryExchange: PrimaryExchange
  operation: string
  sentiment?: number
  status?: string
  relationSeeds: RelationSeed[]
  fxSensitivity: FxSensitivitySeed[]
  commoditySensitivity: CommoditySensitivitySeed[]
}

const relation = (
  ticker: string,
  weight: number,
  kind: RelationKind,
  signal: RelationSignal,
  reason: string,
): RelationSeed => ({ ticker, weight, kind, signal, reason })

const fx = (pair: FxPair, weight: number, reason: string): FxSensitivitySeed => ({ pair, weight, reason })

const commodity = (commodityName: Commodity, weight: number, reason: string): CommoditySensitivitySeed => ({
  commodity: commodityName,
  weight,
  reason,
})

const largeCompanyBlueprints = [
  {
    ticker: 'HBM',
    name: '한빛메모리',
    size: 'large',
    sector: '반도체',
    description: 'AI 서버용 HBM과 파운드리 패키징을 동시에 가진 대형 반도체사',
    basePrice: 84200,
    shares: 7_200_000,
    beta: 1.12,
    revenue: 8.9,
    margin: 0.26,
    backlog: 1.12,
    debtRatio: 0.42,
    quality: 0.72,
    dividendYield: 0.018,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSPI',
    operation: '증설 라인 안정화',
    sentiment: 0.1,
    relationSeeds: [
      relation('NEM', 0.35, 'supplier', 'positive', '특수가스 공급'),
      relation('SEN', 0.28, 'supplier', 'positive', '검사장비 발주'),
      relation('CLD', 0.16, 'customer', 'positive', 'AI 클라우드 증설 수요'),
      relation('NVX', -0.08, 'rival', 'negative', '고대역 메모리 고객 예산 경쟁'),
      relation('FJM', -0.05, 'rival', 'negative', '일본 메모리 고객 인증 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.18, '수출 단가와 달러 매출 비중'), fx('JPY/KRW', -0.04, '일본 경쟁사 가격 압박')],
    commoditySensitivity: [
      commodity('memory', 0.34, 'HBM 현물 가격 사이클'),
      commodity('cloudGpu', 0.12, 'GPU 증설이 메모리 탑재량을 끌어올림'),
    ],
  },
  {
    ticker: 'AUR',
    name: '아우라모빌리티',
    size: 'large',
    sector: '자동차',
    description: '전기차, 상용차, 자율주행 구독 서비스를 묶어 파는 완성차 회사',
    basePrice: 62400,
    shares: 4_400_000,
    beta: 0.92,
    revenue: 6.7,
    margin: 0.11,
    backlog: 1.05,
    debtRatio: 0.64,
    quality: 0.58,
    dividendYield: 0.021,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSPI',
    operation: '신형 전기 SUV 생산',
    sentiment: 0.02,
    relationSeeds: [
      relation('PUR', 0.28, 'supplier', 'positive', '장기 배터리 구매 계약'),
      relation('DRV', 0.12, 'supplier', 'positive', '차량 제어 모듈 납품'),
      relation('EVM', -0.09, 'rival', 'negative', '북미 전기 SUV 가격 경쟁'),
      relation('SAK', -0.05, 'rival', 'negative', '동남아 하이브리드 점유율 경쟁'),
      relation('NEM', 0.08, 'supplier', 'mixed', '전장 소재 조달'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.1, '수출 채산성'), fx('JPY/KRW', -0.04, '일본 완성차 가격 경쟁')],
    commoditySensitivity: [
      commodity('lithium', -0.16, '배터리 원가 전가 지연'),
      commodity('steel', -0.08, '차체 강판 가격'),
    ],
  },
  {
    ticker: 'PUR',
    name: '푸른배터리',
    size: 'large',
    sector: '배터리',
    description: 'LFP와 전고체 파일럿 라인을 동시에 돌리는 2차전지 기업',
    basePrice: 118500,
    shares: 2_900_000,
    beta: 1.25,
    revenue: 5.1,
    margin: 0.13,
    backlog: 1.18,
    debtRatio: 0.82,
    quality: 0.5,
    dividendYield: 0.006,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSPI',
    operation: '수율 개선 태스크포스',
    sentiment: -0.03,
    relationSeeds: [
      relation('AUR', 0.28, 'customer', 'positive', 'EV 출하량 연동'),
      relation('LTH', 0.24, 'supplier', 'mixed', '리튬 정제 원료'),
      relation('NEM', 0.18, 'supplier', 'positive', '전해질 첨가제'),
      relation('EVM', 0.1, 'customer', 'positive', '북미 원통형 배터리 샘플'),
      relation('NAG', -0.06, 'rival', 'negative', '양극재 내재화 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.15, '미국 고객 매출'), fx('JPY/KRW', 0.03, '일본 소재 구매')],
    commoditySensitivity: [
      commodity('lithium', -0.35, '셀 원가 민감도'),
      commodity('nickel', -0.24, '고니켈 제품 믹스'),
    ],
  },
  {
    ticker: 'SEA',
    name: '해온조선',
    size: 'large',
    sector: '조선방산',
    description: 'LNG선, 특수선, 해상풍력 설치선을 수주하는 중후장대 기업',
    basePrice: 35800,
    shares: 5_800_000,
    beta: 0.84,
    revenue: 4.8,
    margin: 0.09,
    backlog: 1.46,
    debtRatio: 0.72,
    quality: 0.57,
    dividendYield: 0.012,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSPI',
    operation: 'LNG선 블록 조립',
    sentiment: 0.07,
    relationSeeds: [
      relation('DAF', 0.14, 'financing', 'positive', '선수금 환급보증'),
      relation('KDR', 0.16, 'supplier', 'positive', '특수선 전투체계 통합'),
      relation('STL', 0.18, 'supplier', 'mixed', '후판 단가와 공급 안정성'),
      relation('TOK', 0.1, 'customer', 'positive', 'LNG 인프라 선박 발주'),
      relation('DOX', -0.05, 'rival', 'negative', '미국 해양 보안선 수주 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.22, '달러 수주잔고'), fx('JPY/KRW', 0.06, '일본 기자재 조달')],
    commoditySensitivity: [commodity('steel', -0.22, '후판 원가'), commodity('lng', 0.1, 'LNG선 발주 심리')],
  },
  {
    ticker: 'HSO',
    name: '해솔에너지',
    size: 'large',
    sector: '에너지',
    description: '태양광, ESS, 전력거래 플랫폼을 가진 에너지 인프라 회사',
    basePrice: 21350,
    shares: 4_900_000,
    beta: 0.76,
    revenue: 2.2,
    margin: 0.1,
    backlog: 1.08,
    debtRatio: 0.67,
    quality: 0.54,
    dividendYield: 0.025,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSPI',
    operation: '전력 입찰 최적화',
    sentiment: 0.01,
    relationSeeds: [
      relation('PUR', 0.16, 'supplier', 'positive', 'ESS 배터리 구매'),
      relation('SEA', 0.1, 'supplier', 'positive', '해상풍력 설치선'),
      relation('ARC', 0.08, 'rival', 'mixed', '글로벌 전력거래 플랫폼 비교'),
      relation('SUN', 0.2, 'supplier', 'positive', '태양광 모듈 공동 조달'),
      relation('TOK', 0.05, 'customer', 'positive', '일본 전력 저장 프로젝트'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.06, '수입 기자재 결제'), fx('JPY/KRW', 0.04, '일본 프로젝트 매출')],
    commoditySensitivity: [commodity('lng', -0.18, '가스 발전 정산 가격'), commodity('copper', -0.08, '송전 설비 원가')],
  },
  {
    ticker: 'DAF',
    name: '다온증권',
    size: 'large',
    sector: '금융',
    description: '리테일 브로커리지, IPO 주관, 프로젝트 금융을 하는 증권사',
    basePrice: 12840,
    shares: 6_300_000,
    beta: 0.98,
    revenue: 1.7,
    margin: 0.14,
    backlog: 0.92,
    debtRatio: 0.88,
    quality: 0.48,
    dividendYield: 0.04,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSPI',
    operation: 'IPO 북빌딩',
    relationSeeds: [
      relation('BIO', 0.1, 'financing', 'positive', '바이오 IPO 주관'),
      relation('SEA', 0.08, 'financing', 'positive', '프로젝트 금융'),
      relation('KDR', 0.06, 'financing', 'positive', '방산 수출 보증'),
      relation('MBB', 0.07, 'rival', 'mixed', '글로벌 IB 수수료 벤치마크'),
      relation('FND', 0.12, 'platform', 'positive', '핀테크 제휴 계좌'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.05, '외국인 수급 변동'), fx('JPY/KRW', 0.02, '일본 자금 유입')],
    commoditySensitivity: [commodity('biotechFunding', 0.16, '성장주 자금 조달 심리')],
  },
  {
    ticker: 'KDR',
    name: '케이디펜스',
    size: 'large',
    sector: '조선방산',
    description: '함정 전투체계, 지상 로봇, 방산용 센서를 묶어 공급하는 방산 기업',
    basePrice: 51700,
    shares: 3_700_000,
    beta: 0.89,
    revenue: 3.6,
    margin: 0.15,
    backlog: 1.34,
    debtRatio: 0.51,
    quality: 0.66,
    dividendYield: 0.014,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSPI',
    operation: '수출형 무인체계 시험',
    sentiment: 0.05,
    relationSeeds: [
      relation('SEA', 0.16, 'customer', 'positive', '특수선 전투체계'),
      relation('OPT', 0.18, 'supplier', 'positive', '광학 센서 모듈'),
      relation('DRN', 0.2, 'supplier', 'positive', '정찰 드론 공동 개발'),
      relation('SEN', 0.08, 'supplier', 'mixed', '검사 센서 조달'),
      relation('KUR', -0.06, 'rival', 'negative', '일본 방산 입찰 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.16, '달러 방산 수출'), fx('JPY/KRW', -0.02, '일본 경쟁사 가격')],
    commoditySensitivity: [commodity('rareEarth', -0.12, '센서 자석 원가'), commodity('steel', -0.1, '차량 플랫폼 원가')],
  },
  {
    ticker: 'NVX',
    name: 'Novex Compute',
    size: 'large',
    sector: '반도체',
    description: 'GPU 가속기와 네트워크 칩을 묶어 데이터센터에 파는 미국 반도체사',
    basePrice: 156000,
    shares: 8_100_000,
    beta: 1.22,
    revenue: 10.8,
    margin: 0.29,
    backlog: 1.24,
    debtRatio: 0.3,
    quality: 0.8,
    dividendYield: 0.006,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '차세대 가속기 랙 출하',
    sentiment: 0.12,
    relationSeeds: [
      relation('HBM', 0.2, 'supplier', 'positive', '고대역 메모리 탑재'),
      relation('CLD', 0.24, 'customer', 'positive', '클라우드 GPU 주문'),
      relation('GUM', 0.08, 'customer', 'positive', 'AI 에이전트 추론 수요'),
      relation('FJM', 0.1, 'supplier', 'mixed', '메모리 보조 공급'),
      relation('AXI', 0.08, 'supplier', 'positive', '노광 장비 부품'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.24, '달러 매출의 원화 환산'), fx('USD/JPY', 0.04, '일본 소재 구매력')],
    commoditySensitivity: [
      commodity('cloudGpu', 0.28, 'AI 인프라 투자 사이클'),
      commodity('memory', 0.18, 'HBM 가격과 공급'),
    ],
  },
  {
    ticker: 'CLD',
    name: 'CloudHaven',
    size: 'large',
    sector: 'AI소프트웨어',
    description: '기업용 클라우드와 AI 에이전트 런타임을 제공하는 미국 소프트웨어 기업',
    basePrice: 132500,
    shares: 6_600_000,
    beta: 1.18,
    revenue: 9.4,
    margin: 0.24,
    backlog: 1.2,
    debtRatio: 0.24,
    quality: 0.78,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: 'AI 런타임 사용량 증대',
    sentiment: 0.09,
    relationSeeds: [
      relation('NVX', 0.22, 'supplier', 'mixed', 'GPU 서버 조달'),
      relation('HBM', 0.12, 'supplier', 'positive', '메모리 공급 안정성'),
      relation('GUM', -0.08, 'rival', 'negative', '아시아 기업용 AI 계약 경쟁'),
      relation('NET', 0.1, 'platform', 'positive', '네트워크 보안 번들'),
      relation('STG', 0.05, 'customer', 'positive', '게임 서버 운영'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.19, '달러 구독 매출 환산'), fx('USD/JPY', 0.07, '일본 고객 결제')],
    commoditySensitivity: [commodity('cloudGpu', -0.2, 'GPU 임대 비용'), commodity('adSpending', 0.08, 'SaaS 마케팅 수요')],
  },
  {
    ticker: 'EVM',
    name: 'Evermotion Auto',
    size: 'large',
    sector: '자동차',
    description: '전기 픽업, 충전 구독, 배터리 리스를 결합한 미국 완성차 회사',
    basePrice: 74400,
    shares: 5_400_000,
    beta: 1.01,
    revenue: 7.8,
    margin: 0.1,
    backlog: 1.04,
    debtRatio: 0.59,
    quality: 0.62,
    dividendYield: 0.018,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '상용 전기 픽업 증산',
    sentiment: 0.01,
    relationSeeds: [
      relation('PUR', 0.12, 'supplier', 'positive', '원통형 셀 샘플'),
      relation('BAT', 0.16, 'supplier', 'positive', '팩 조립 외주'),
      relation('AUR', -0.1, 'rival', 'negative', '전기 SUV 할인 경쟁'),
      relation('SAK', -0.06, 'rival', 'negative', '하이브리드 고객 이탈'),
      relation('LTH', 0.08, 'supplier', 'mixed', '리튬 조달'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.11, '한국 배터리 구매 계약'), fx('USD/JPY', -0.03, '일본 부품 조달')],
    commoditySensitivity: [commodity('lithium', -0.21, '배터리 셀 원가'), commodity('steel', -0.07, '차체 원가')],
  },
  {
    ticker: 'BIOV',
    name: 'BioVanta',
    size: 'large',
    sector: '바이오',
    description: '항체 치료제, 세포치료제, 위탁생산을 함께 운영하는 미국 바이오 기업',
    basePrice: 88500,
    shares: 3_200_000,
    beta: 1.08,
    revenue: 4.9,
    margin: 0.18,
    backlog: 0.98,
    debtRatio: 0.33,
    quality: 0.73,
    dividendYield: 0.004,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '항체 치료제 적응증 확대',
    sentiment: 0.04,
    relationSeeds: [
      relation('BIO', 0.1, 'customer', 'positive', '후보물질 공동 임상'),
      relation('MED', 0.08, 'supplier', 'positive', '진단 키트 동반 사용'),
      relation('KAI', -0.07, 'rival', 'negative', '면역질환 파이프라인 경쟁'),
      relation('CRO', 0.12, 'supplier', 'mixed', '임상 생산 외주'),
      relation('DAF', 0.04, 'financing', 'positive', '한국 바이오 투자 수요'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.08, '해외 라이선스 매출'), fx('USD/JPY', 0.05, '일본 임상 비용')],
    commoditySensitivity: [commodity('biotechFunding', 0.2, '임상 자금 조달 환경')],
  },
  {
    ticker: 'STG',
    name: 'StarForge Games',
    size: 'large',
    sector: '게임콘텐츠',
    description: '라이브 서비스 게임과 팬 커뮤니티 플랫폼을 운영하는 미국 콘텐츠 기업',
    basePrice: 40600,
    shares: 4_800_000,
    beta: 1.34,
    revenue: 3.4,
    margin: 0.21,
    backlog: 0.96,
    debtRatio: 0.2,
    quality: 0.64,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '크로스플랫폼 시즌 업데이트',
    sentiment: 0.02,
    relationSeeds: [
      relation('PIX', -0.07, 'rival', 'negative', '서브컬처 이용자 시간 경쟁'),
      relation('CLD', 0.08, 'platform', 'mixed', '게임 서버 비용'),
      relation('GUM', 0.07, 'supplier', 'positive', 'AI 제작 도구'),
      relation('PLY', 0.1, 'supplier', 'positive', '인디 퍼블리싱 파이프라인'),
      relation('KOM', -0.04, 'rival', 'negative', '일본 콘솔 IP 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.08, '글로벌 결제 매출'), fx('USD/JPY', 0.07, '일본 유저 매출')],
    commoditySensitivity: [commodity('cloudGpu', -0.08, '렌더링 서버 비용'), commodity('adSpending', 0.16, '성과형 광고 단가')],
  },
  {
    ticker: 'ARC',
    name: 'ArcGrid Energy',
    size: 'large',
    sector: '에너지',
    description: '전력망 소프트웨어, ESS, 재생에너지 운영을 결합한 미국 에너지 기업',
    basePrice: 52700,
    shares: 5_200_000,
    beta: 0.72,
    revenue: 5.6,
    margin: 0.12,
    backlog: 1.1,
    debtRatio: 0.68,
    quality: 0.6,
    dividendYield: 0.032,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '주파수 조정 ESS 입찰',
    sentiment: 0.02,
    relationSeeds: [
      relation('HSO', 0.09, 'rival', 'mixed', '전력거래 알고리즘 비교'),
      relation('TOK', 0.07, 'customer', 'positive', '일본 계통 안정화 프로젝트'),
      relation('URN', 0.06, 'supplier', 'mixed', '원전 PPA 헤지'),
      relation('SUN', 0.1, 'supplier', 'positive', '태양광 모듈 조달'),
      relation('PUR', 0.06, 'supplier', 'positive', 'ESS 셀 공급'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.07, '아시아 프로젝트 환산'), fx('USD/JPY', 0.04, '일본 전력 프로젝트')],
    commoditySensitivity: [commodity('oil', 0.08, '전력 가격 헤지'), commodity('lng', -0.15, '가스 발전 경쟁 원가')],
  },
  {
    ticker: 'MBB',
    name: 'Meridian Bank',
    size: 'large',
    sector: '금융',
    description: 'IB, 기업대출, 글로벌 결제망을 운영하는 미국 대형 금융사',
    basePrice: 33200,
    shares: 7_400_000,
    beta: 0.86,
    revenue: 5.9,
    margin: 0.19,
    backlog: 0.9,
    debtRatio: 0.91,
    quality: 0.56,
    dividendYield: 0.038,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '기업대출 스프레드 관리',
    relationSeeds: [
      relation('DAF', 0.05, 'rival', 'mixed', '아시아 IB 딜 경쟁'),
      relation('SUMI', 0.08, 'financing', 'positive', '달러 조달 스왑'),
      relation('FND', 0.1, 'platform', 'positive', '핀테크 계좌 인프라'),
      relation('BIOV', 0.06, 'financing', 'positive', '바이오 채권 발행'),
      relation('TRS', 0.08, 'customer', 'positive', '인프라 금융 매출'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.04, '신흥국 자금 흐름'), fx('USD/JPY', -0.03, '엔 캐리 트레이드 리스크')],
    commoditySensitivity: [commodity('biotechFunding', 0.1, '성장주 딜 수수료')],
  },
  {
    ticker: 'FJM',
    name: 'Fuji Memory',
    size: 'large',
    sector: '반도체',
    description: '고신뢰 메모리와 패키징 기판을 공급하는 일본 반도체 기업',
    basePrice: 68200,
    shares: 5_100_000,
    beta: 1.05,
    revenue: 6.2,
    margin: 0.22,
    backlog: 1.08,
    debtRatio: 0.35,
    quality: 0.7,
    dividendYield: 0.015,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Prime',
    operation: '고신뢰 메모리 인증',
    sentiment: 0.04,
    relationSeeds: [
      relation('HBM', -0.07, 'rival', 'negative', 'HBM 고객사 승인 경쟁'),
      relation('NVX', 0.11, 'customer', 'positive', 'AI 가속기 메모리 납품'),
      relation('MIZ', 0.14, 'supplier', 'positive', '식각 공정 장비'),
      relation('NAG', 0.09, 'supplier', 'mixed', '패키징 소재'),
      relation('YAM', 0.1, 'supplier', 'positive', '웨이퍼 센서'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.12, '엔화 매출 환산'), fx('USD/JPY', 0.09, '달러 고객 주문')],
    commoditySensitivity: [commodity('memory', 0.24, '메모리 가격 사이클'), commodity('rareEarth', -0.08, '특수 소재 원가')],
  },
  {
    ticker: 'SAK',
    name: 'Sakura Mobility',
    size: 'large',
    sector: '자동차',
    description: '하이브리드, 소형 전기차, 로봇 택시 플랫폼을 운영하는 일본 완성차 회사',
    basePrice: 54600,
    shares: 4_700_000,
    beta: 0.83,
    revenue: 6.9,
    margin: 0.09,
    backlog: 1.02,
    debtRatio: 0.53,
    quality: 0.64,
    dividendYield: 0.023,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Prime',
    operation: '하이브리드 파워트레인 개선',
    sentiment: 0.01,
    relationSeeds: [
      relation('AUR', -0.06, 'rival', 'negative', '아시아 전기차 점유율 경쟁'),
      relation('EVM', -0.05, 'rival', 'negative', '미국 전기 픽업 대비 하이브리드 수요'),
      relation('FJM', 0.08, 'supplier', 'positive', '차량용 메모리'),
      relation('HIK', 0.14, 'supplier', 'positive', '전장 모듈'),
      relation('PUR', 0.06, 'supplier', 'mixed', '배터리 셀 가격 협상'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.1, '엔화 매출 환산'), fx('USD/JPY', 0.12, '미국 수출 채산성')],
    commoditySensitivity: [commodity('steel', -0.08, '차체 원가'), commodity('lithium', -0.09, '소형 EV 셀 원가')],
  },
  {
    ticker: 'KAI',
    name: 'Kaizen Pharma',
    size: 'large',
    sector: '바이오',
    description: '면역질환 치료제와 항암 보조제를 개발하는 일본 제약사',
    basePrice: 73100,
    shares: 2_600_000,
    beta: 0.94,
    revenue: 3.7,
    margin: 0.17,
    backlog: 0.94,
    debtRatio: 0.28,
    quality: 0.68,
    dividendYield: 0.012,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Prime',
    operation: '면역질환 3상 준비',
    sentiment: 0.03,
    relationSeeds: [
      relation('BIOV', -0.06, 'rival', 'negative', '면역질환 파이프라인 경쟁'),
      relation('BIO', 0.08, 'customer', 'positive', '공동 후보물질 옵션'),
      relation('ORI', 0.12, 'supplier', 'positive', '오가노이드 효능 평가'),
      relation('CRO', 0.06, 'supplier', 'mixed', '임상 생산 슬롯'),
      relation('SUMI', 0.05, 'financing', 'positive', '엔화 회사채 발행'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.08, '엔화 라이선스 수익'), fx('USD/JPY', -0.04, '미국 임상 비용')],
    commoditySensitivity: [commodity('biotechFunding', 0.18, '임상 자금 시장')],
  },
  {
    ticker: 'TOK',
    name: 'Tokyo Tide Energy',
    size: 'large',
    sector: '에너지',
    description: 'LNG 터미널, 해상풍력, 전력 저장소를 운영하는 일본 에너지 기업',
    basePrice: 38800,
    shares: 4_400_000,
    beta: 0.7,
    revenue: 4.4,
    margin: 0.11,
    backlog: 1.06,
    debtRatio: 0.62,
    quality: 0.59,
    dividendYield: 0.029,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Prime',
    operation: '해상풍력 송전 접속',
    relationSeeds: [
      relation('ARC', 0.09, 'supplier', 'positive', '전력망 소프트웨어'),
      relation('HSO', 0.06, 'supplier', 'positive', 'ESS 운영 기술'),
      relation('SEA', 0.1, 'supplier', 'positive', 'LNG선 발주'),
      relation('NAG', 0.06, 'supplier', 'mixed', '터빈 소재'),
      relation('ONS', 0.1, 'customer', 'positive', '지역 마이크로그리드'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.07, '엔화 배당 재원'), fx('USD/JPY', -0.08, '달러 LNG 구매')],
    commoditySensitivity: [commodity('lng', -0.22, '연료 구매 단가'), commodity('copper', -0.06, '송전망 투자 비용')],
  },
  {
    ticker: 'NAG',
    name: 'Nagomi Materials',
    size: 'large',
    sector: '소재',
    description: '양극재 전구체, 세라믹 기판, 특수 첨가제를 생산하는 일본 소재 기업',
    basePrice: 28900,
    shares: 4_100_000,
    beta: 0.96,
    revenue: 3.2,
    margin: 0.13,
    backlog: 1.0,
    debtRatio: 0.44,
    quality: 0.63,
    dividendYield: 0.019,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Prime',
    operation: '세라믹 기판 수율 개선',
    relationSeeds: [
      relation('PUR', 0.08, 'customer', 'positive', '양극재 샘플 공급'),
      relation('FJM', 0.1, 'customer', 'positive', '패키징 소재'),
      relation('NEM', -0.06, 'rival', 'negative', '첨단 소재 가격 경쟁'),
      relation('KOB', 0.12, 'supplier', 'mixed', '희소금속 조달'),
      relation('TSC', 0.08, 'customer', 'positive', '일본 배터리 소재'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.09, '엔화 매출 환산'), fx('USD/JPY', -0.05, '달러 원재료 구매')],
    commoditySensitivity: [commodity('nickel', -0.16, '양극재 원가'), commodity('rareEarth', -0.14, '첨가제 원가')],
  },
  {
    ticker: 'SUMI',
    name: 'Sumire Bank',
    size: 'large',
    sector: '금융',
    description: '무역금융, 리스, 자산운용을 겸하는 일본 금융 그룹',
    basePrice: 24500,
    shares: 5_900_000,
    beta: 0.78,
    revenue: 4.1,
    margin: 0.16,
    backlog: 0.88,
    debtRatio: 0.9,
    quality: 0.55,
    dividendYield: 0.036,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Prime',
    operation: '무역금융 마진 관리',
    relationSeeds: [
      relation('MBB', 0.08, 'financing', 'positive', '달러 조달 스왑'),
      relation('DAF', 0.05, 'rival', 'mixed', '아시아 IPO 고객 경쟁'),
      relation('TOK', 0.08, 'financing', 'positive', '에너지 프로젝트 대출'),
      relation('KAI', 0.04, 'financing', 'positive', '제약 회사채 발행'),
      relation('SHN', 0.12, 'platform', 'positive', '리스 포트폴리오 공동 판매'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.06, '엔화 배당 환산'), fx('USD/JPY', -0.06, '달러 조달 비용')],
    commoditySensitivity: [commodity('biotechFunding', 0.06, '성장기업 금융 수요')],
  },
] satisfies CompanyBlueprint[]

const smallCompanyBlueprints = [
  {
    ticker: 'SEN',
    name: '센서웍스',
    size: 'small',
    sector: '반도체',
    description: '웨이퍼 검사장비와 고속 센서 모듈을 만드는 성장주',
    basePrice: 18750,
    shares: 2_500_000,
    beta: 1.45,
    revenue: 1.4,
    margin: 0.18,
    backlog: 1.24,
    debtRatio: 0.58,
    quality: 0.55,
    dividendYield: 0.002,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '검사장비 고객 승인',
    sentiment: 0.08,
    relationSeeds: [
      relation('HBM', 0.3, 'customer', 'positive', '장비 고객사'),
      relation('FJM', 0.09, 'customer', 'positive', '일본 메모리 인증 장비'),
      relation('OPT', -0.04, 'rival', 'negative', '고속 센서 가격 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.08, '수출 장비 매출')],
    commoditySensitivity: [commodity('memory', 0.1, '메모리 투자 사이클')],
  },
  {
    ticker: 'NEM',
    name: '네온소재',
    size: 'small',
    sector: '소재',
    description: '네온가스, 포토레지스트 원재료, 배터리 전해질을 공급하는 소재사',
    basePrice: 9320,
    shares: 3_100_000,
    beta: 1.28,
    revenue: 1.8,
    margin: 0.16,
    backlog: 0.98,
    debtRatio: 0.49,
    quality: 0.52,
    dividendYield: 0.008,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '원재료 재고 조달',
    sentiment: -0.02,
    relationSeeds: [
      relation('HBM', 0.26, 'customer', 'positive', '반도체 소재 수요'),
      relation('PUR', 0.18, 'customer', 'positive', '전해질 공급'),
      relation('NAG', -0.05, 'rival', 'negative', '특수 소재 단가 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.09, '수입 원재료 결제')],
    commoditySensitivity: [commodity('rareEarth', -0.12, '특수 가스 원료'), commodity('lithium', -0.08, '전해질 원가')],
  },
  {
    ticker: 'GUM',
    name: '구름소프트',
    size: 'small',
    sector: 'AI소프트웨어',
    description: '기업용 AI 에이전트와 데이터센터 운영 도구를 제공하는 소프트웨어사',
    basePrice: 27600,
    shares: 2_200_000,
    beta: 1.38,
    revenue: 0.9,
    margin: 0.22,
    backlog: 1.32,
    debtRatio: 0.18,
    quality: 0.64,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: 'AI 에이전트 PoC 납품',
    sentiment: 0.16,
    status: '과열주의',
    relationSeeds: [
      relation('HBM', 0.18, 'supplier', 'mixed', 'AI 반도체 투자'),
      relation('AUR', 0.08, 'customer', 'positive', '차량 OS 계약'),
      relation('CLD', -0.08, 'rival', 'negative', '기업 AI 플랫폼 경쟁'),
      relation('PIX', 0.1, 'customer', 'positive', '콘텐츠 생성툴'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.03, '클라우드 비용 결제')],
    commoditySensitivity: [commodity('cloudGpu', -0.18, '추론 서버 비용')],
  },
  {
    ticker: 'BIO',
    name: '셀바이오랩',
    size: 'small',
    sector: '바이오',
    description: '면역항암제 후보물질과 CDMO 위탁생산을 병행하는 바이오텍',
    basePrice: 42100,
    shares: 1_700_000,
    beta: 1.58,
    revenue: 0.42,
    margin: -0.08,
    backlog: 0.62,
    debtRatio: 0.36,
    quality: 0.46,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '2상 환자 모집',
    sentiment: 0.04,
    status: '변동성',
    relationSeeds: [
      relation('DAF', 0.08, 'financing', 'positive', '임상 자금 조달'),
      relation('BIOV', 0.1, 'customer', 'positive', '공동 임상 옵션'),
      relation('KAI', 0.05, 'rival', 'mixed', '면역질환 데이터 비교'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.05, '해외 CRO 비용')],
    commoditySensitivity: [commodity('biotechFunding', 0.24, '임상 자금 조달 심리')],
  },
  {
    ticker: 'PIX',
    name: '픽셀엔터',
    size: 'small',
    sector: '게임콘텐츠',
    description: '라이브 서비스 게임과 버추얼 아이돌 IP를 운영하는 콘텐츠 기업',
    basePrice: 14620,
    shares: 3_600_000,
    beta: 1.34,
    revenue: 0.76,
    margin: 0.19,
    backlog: 0.88,
    debtRatio: 0.23,
    quality: 0.5,
    dividendYield: 0.004,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '신규 시즌 업데이트',
    sentiment: -0.04,
    relationSeeds: [
      relation('GUM', 0.16, 'supplier', 'positive', 'AI 제작툴'),
      relation('STG', -0.07, 'rival', 'negative', '글로벌 라이브 서비스 경쟁'),
      relation('IDP', 0.06, 'customer', 'positive', '버추얼 IP 공동 행사'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.04, '해외 결제 매출')],
    commoditySensitivity: [commodity('adSpending', 0.14, '신작 마케팅 효율')],
  },
  {
    ticker: 'LTH',
    name: '리튬하버',
    size: 'small',
    sector: '소재',
    description: '염호 지분과 리튬 정제 설비를 함께 가진 배터리 소재 기업',
    basePrice: 15880,
    shares: 2_800_000,
    beta: 1.52,
    revenue: 0.82,
    margin: 0.11,
    backlog: 1.05,
    debtRatio: 0.63,
    quality: 0.43,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '탄산리튬 정제 라인 시운전',
    relationSeeds: [
      relation('PUR', 0.24, 'customer', 'positive', '셀 업체 장기 공급'),
      relation('EVM', 0.08, 'customer', 'positive', '북미 EV 원료 조달'),
      relation('RCY', -0.04, 'rival', 'negative', '재활용 원료와 가격 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.12, '달러 광물 결제')],
    commoditySensitivity: [commodity('lithium', 0.38, '리튬 판매 단가')],
  },
  {
    ticker: 'DRV',
    name: '드라이브온',
    size: 'small',
    sector: '자동차',
    description: '전기차 구동 인버터와 차량 제어기를 공급하는 전장 부품사',
    basePrice: 11740,
    shares: 2_400_000,
    beta: 1.18,
    revenue: 1.1,
    margin: 0.1,
    backlog: 1.14,
    debtRatio: 0.47,
    quality: 0.51,
    dividendYield: 0.006,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '전력반도체 인버터 양산',
    relationSeeds: [
      relation('AUR', 0.2, 'customer', 'positive', '전기 SUV 제어기 납품'),
      relation('HIK', -0.04, 'rival', 'negative', '일본 전장 모듈 가격 경쟁'),
      relation('OPT', 0.06, 'supplier', 'positive', '광센서 제어 부품'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.05, '수출 전장 부품'), fx('JPY/KRW', -0.04, '일본 경쟁 부품')],
    commoditySensitivity: [commodity('copper', -0.1, '모터 권선 원가')],
  },
  {
    ticker: 'OPT',
    name: '옵틱스나노',
    size: 'small',
    sector: '반도체',
    description: '방산과 반도체용 광학 센서를 만드는 나노 공정 기업',
    basePrice: 22450,
    shares: 1_900_000,
    beta: 1.36,
    revenue: 0.68,
    margin: 0.17,
    backlog: 1.16,
    debtRatio: 0.31,
    quality: 0.57,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '저조도 센서 신뢰성 시험',
    relationSeeds: [
      relation('KDR', 0.18, 'customer', 'positive', '방산 광학 모듈'),
      relation('DRV', 0.06, 'customer', 'positive', '차량 센서 부품'),
      relation('SEN', -0.05, 'rival', 'negative', '검사 센서 수주 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.07, '방산 수출 부품')],
    commoditySensitivity: [commodity('rareEarth', -0.1, '광학 소재 원가')],
  },
  {
    ticker: 'CDO',
    name: '씨도오션',
    size: 'small',
    sector: '조선방산',
    description: '선박용 자동화 밸브와 해양 통신 장비를 납품하는 조선 기자재사',
    basePrice: 8040,
    shares: 3_200_000,
    beta: 1.08,
    revenue: 0.74,
    margin: 0.08,
    backlog: 1.22,
    debtRatio: 0.56,
    quality: 0.48,
    dividendYield: 0.009,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: 'LNG선 자동화 밸브 납품',
    relationSeeds: [
      relation('SEA', 0.24, 'customer', 'positive', 'LNG선 기자재'),
      relation('MIR', 0.05, 'rival', 'mixed', '일본 해양 기자재 입찰'),
      relation('STL', 0.08, 'supplier', 'mixed', '특수강 소재'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.12, '달러 수주 단가')],
    commoditySensitivity: [commodity('steel', -0.16, '밸브 소재 원가'), commodity('lng', 0.08, 'LNG선 발주')],
  },
  {
    ticker: 'SUN',
    name: '새빛솔라',
    size: 'small',
    sector: '에너지',
    description: '고효율 태양광 모듈과 상업용 인버터를 공급하는 에너지 기업',
    basePrice: 10550,
    shares: 3_500_000,
    beta: 1.16,
    revenue: 0.93,
    margin: 0.09,
    backlog: 1.12,
    debtRatio: 0.52,
    quality: 0.5,
    dividendYield: 0.005,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '상업용 태양광 모듈 출하',
    relationSeeds: [
      relation('HSO', 0.2, 'customer', 'positive', '국내 ESS 프로젝트'),
      relation('ARC', 0.08, 'customer', 'positive', '미국 마이크로그리드 납품'),
      relation('AKR', -0.04, 'rival', 'negative', '일본 태양광 가격 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.09, '수출 모듈 매출')],
    commoditySensitivity: [commodity('copper', -0.09, '인버터 원가')],
  },
  {
    ticker: 'FND',
    name: '핀브릿지',
    size: 'small',
    sector: '금융',
    description: '소상공인 신용평가와 계좌 연동 결제 서비스를 제공하는 핀테크사',
    basePrice: 6720,
    shares: 4_000_000,
    beta: 1.22,
    revenue: 0.38,
    margin: 0.12,
    backlog: 0.84,
    debtRatio: 0.41,
    quality: 0.45,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '대안신용평가 모델 업데이트',
    relationSeeds: [
      relation('DAF', 0.12, 'platform', 'positive', '제휴 계좌 유입'),
      relation('MBB', 0.08, 'financing', 'positive', '글로벌 결제망 제휴'),
      relation('PAY', -0.06, 'rival', 'negative', '소상공인 결제 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.03, '해외 결제 원가')],
    commoditySensitivity: [commodity('adSpending', 0.06, '가맹점 모집 효율')],
  },
  {
    ticker: 'BAT',
    name: '바른팩',
    size: 'small',
    sector: '배터리',
    description: '원통형 셀 팩 조립과 BMS를 공급하는 배터리 모듈 기업',
    basePrice: 24650,
    shares: 2_100_000,
    beta: 1.4,
    revenue: 1.02,
    margin: 0.08,
    backlog: 1.21,
    debtRatio: 0.66,
    quality: 0.47,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: 'BMS 펌웨어 검증',
    relationSeeds: [
      relation('PUR', 0.22, 'supplier', 'positive', '셀 공급 안정성'),
      relation('EVM', 0.16, 'customer', 'positive', '전기 픽업 팩 외주'),
      relation('TSC', -0.05, 'rival', 'negative', '일본 팩 모듈 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.1, '북미 고객 매출')],
    commoditySensitivity: [commodity('lithium', -0.12, '셀 원가 연동'), commodity('copper', -0.07, 'BMS 부품 원가')],
  },
  {
    ticker: 'CRO',
    name: '크로젠CDMO',
    size: 'small',
    sector: '바이오',
    description: '임상용 바이오 의약품 생산과 분석 서비스를 제공하는 CDMO 기업',
    basePrice: 18980,
    shares: 1_600_000,
    beta: 1.32,
    revenue: 0.58,
    margin: 0.12,
    backlog: 1.18,
    debtRatio: 0.39,
    quality: 0.55,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '임상 생산 슬롯 배정',
    relationSeeds: [
      relation('BIOV', 0.12, 'customer', 'positive', '항체 생산 위탁'),
      relation('KAI', 0.06, 'customer', 'positive', '일본 임상 생산'),
      relation('BIO', 0.08, 'customer', 'mixed', '국내 후보물질 생산'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.07, '달러 위탁생산 매출')],
    commoditySensitivity: [commodity('biotechFunding', 0.18, '임상 고객 자금 여력')],
  },
  {
    ticker: 'NET',
    name: '넷플로우',
    size: 'small',
    sector: 'AI소프트웨어',
    description: 'API 게이트웨이와 AI 보안 관제를 묶어 제공하는 B2B 소프트웨어사',
    basePrice: 13540,
    shares: 2_700_000,
    beta: 1.26,
    revenue: 0.62,
    margin: 0.2,
    backlog: 1.1,
    debtRatio: 0.2,
    quality: 0.58,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: 'AI 보안 관제 신규 고객 온보딩',
    relationSeeds: [
      relation('CLD', 0.1, 'platform', 'positive', '클라우드 마켓플레이스'),
      relation('GUM', 0.08, 'customer', 'positive', 'AI 에이전트 보안 연동'),
      relation('NEX', -0.04, 'rival', 'negative', 'API 자동화 제품 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.04, '클라우드 사용료')],
    commoditySensitivity: [commodity('cloudGpu', -0.1, '보안 모델 추론 비용')],
  },
  {
    ticker: 'STL',
    name: '스틸루트',
    size: 'small',
    sector: '소재',
    description: '조선용 후판과 고강도 특수강 유통을 하는 소재 기업',
    basePrice: 7340,
    shares: 4_200_000,
    beta: 1.05,
    revenue: 1.25,
    margin: 0.07,
    backlog: 1.0,
    debtRatio: 0.7,
    quality: 0.42,
    dividendYield: 0.012,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '후판 재고 회전율 관리',
    relationSeeds: [
      relation('SEA', 0.18, 'customer', 'positive', '조선 후판 공급'),
      relation('CDO', 0.08, 'customer', 'positive', '밸브 소재 공급'),
      relation('PCB', -0.04, 'rival', 'negative', '특수강 유통 마진 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.08, '수입 철강 결제')],
    commoditySensitivity: [commodity('steel', 0.26, '후판 판매 단가')],
  },
  {
    ticker: 'DRN',
    name: '드론실드',
    size: 'small',
    sector: '조선방산',
    description: '정찰 드론과 전파 방해 대응 장비를 만드는 방산 스타트업',
    basePrice: 29800,
    shares: 1_800_000,
    beta: 1.48,
    revenue: 0.5,
    margin: 0.09,
    backlog: 1.36,
    debtRatio: 0.44,
    quality: 0.5,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '수출형 정찰 드론 시험비행',
    relationSeeds: [
      relation('KDR', 0.2, 'customer', 'positive', '무인체계 공동 개발'),
      relation('OPT', 0.08, 'supplier', 'positive', '광학 센서 모듈'),
      relation('IND', -0.05, 'rival', 'negative', '미국 방산 드론 입찰 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.14, '달러 수출 계약')],
    commoditySensitivity: [commodity('rareEarth', -0.1, '모터와 센서 소재')],
  },
  {
    ticker: 'GME',
    name: '게임바다',
    size: 'small',
    sector: '게임콘텐츠',
    description: '모바일 퍼즐 RPG와 웹툰 IP 게임을 운영하는 중소 게임사',
    basePrice: 5580,
    shares: 4_600_000,
    beta: 1.3,
    revenue: 0.34,
    margin: 0.15,
    backlog: 0.78,
    debtRatio: 0.19,
    quality: 0.44,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '웹툰 IP 이벤트 출시',
    relationSeeds: [
      relation('PIX', 0.1, 'rival', 'mixed', '서브컬처 유저 이벤트 경쟁'),
      relation('GUM', 0.06, 'supplier', 'positive', '자동 번역 도구'),
      relation('PLY', -0.04, 'rival', 'negative', '인디 퍼블리싱 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.05, '해외 앱마켓 매출')],
    commoditySensitivity: [commodity('adSpending', 0.14, '유저 획득 단가')],
  },
  {
    ticker: 'RCY',
    name: '리사이클메탈',
    size: 'small',
    sector: '소재',
    description: '폐배터리에서 니켈과 리튬을 회수하는 도시광산 기업',
    basePrice: 12260,
    shares: 2_900_000,
    beta: 1.42,
    revenue: 0.7,
    margin: 0.1,
    backlog: 1.02,
    debtRatio: 0.58,
    quality: 0.46,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '블랙매스 회수율 개선',
    relationSeeds: [
      relation('PUR', 0.1, 'customer', 'positive', '재활용 소재 공급'),
      relation('LTH', -0.05, 'rival', 'negative', '신규 리튬 원료와 경쟁'),
      relation('NIR', -0.04, 'rival', 'negative', '일본 재활용 업체와 입찰 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.04, '금속 판매 기준가')],
    commoditySensitivity: [commodity('nickel', 0.24, '회수 금속 판매 단가'), commodity('lithium', 0.18, '리튬 회수 가치')],
  },
  {
    ticker: 'ESS',
    name: '이지스토리지',
    size: 'small',
    sector: '배터리',
    description: '상업용 ESS 랙과 전력 운영 소프트웨어를 공급하는 배터리 시스템사',
    basePrice: 17320,
    shares: 2_600_000,
    beta: 1.3,
    revenue: 0.88,
    margin: 0.09,
    backlog: 1.2,
    debtRatio: 0.61,
    quality: 0.49,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '상업용 ESS 랙 출하',
    relationSeeds: [
      relation('HSO', 0.18, 'customer', 'positive', '국내 전력 저장 프로젝트'),
      relation('PUR', 0.14, 'supplier', 'mixed', '배터리 셀 조달'),
      relation('SOL', -0.04, 'rival', 'negative', '미국 마이크로그리드 ESS 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.07, '해외 ESS 매출')],
    commoditySensitivity: [commodity('lithium', -0.16, '셀 원가'), commodity('copper', -0.06, '전력 부품 원가')],
  },
  {
    ticker: 'MED',
    name: '메디스캔',
    size: 'small',
    sector: '바이오',
    description: '동반진단 키트와 병리 AI 분석 서비스를 제공하는 헬스케어 기업',
    basePrice: 9700,
    shares: 3_300_000,
    beta: 1.24,
    revenue: 0.45,
    margin: 0.13,
    backlog: 0.86,
    debtRatio: 0.29,
    quality: 0.52,
    dividendYield: 0,
    primaryCountry: 'KR',
    primaryCurrency: 'KRW',
    primaryExchange: 'KOSDAQ',
    operation: '동반진단 키트 병원 검증',
    relationSeeds: [
      relation('BIOV', 0.08, 'customer', 'positive', '항체 치료제 동반진단'),
      relation('BIO', 0.06, 'customer', 'positive', '임상 데이터 분석'),
      relation('HEL', -0.04, 'rival', 'negative', '미국 진단 플랫폼 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.05, '수출 진단 키트')],
    commoditySensitivity: [commodity('biotechFunding', 0.12, '병원 연구비 집행')],
  },
  {
    ticker: 'AXI',
    name: 'Axion Lithography',
    size: 'small',
    sector: '반도체',
    description: '첨단 노광 장비용 정밀 스테이지와 광원을 공급하는 미국 장비사',
    basePrice: 31200,
    shares: 1_900_000,
    beta: 1.38,
    revenue: 1.1,
    margin: 0.2,
    backlog: 1.28,
    debtRatio: 0.34,
    quality: 0.6,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '노광 스테이지 고객 평가',
    relationSeeds: [
      relation('NVX', 0.08, 'customer', 'positive', '첨단 공정 투자'),
      relation('HBM', 0.07, 'customer', 'positive', '패키징 공정 장비'),
      relation('MIZ', -0.04, 'rival', 'negative', '일본 식각 장비 대체 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.09, '달러 장비 매출')],
    commoditySensitivity: [commodity('memory', 0.12, '반도체 설비 투자')],
  },
  {
    ticker: 'CHP',
    name: 'Chiplet Works',
    size: 'small',
    sector: '반도체',
    description: '칩렛 인터커넥트 IP와 테스트 보드를 개발하는 팹리스 기업',
    basePrice: 18400,
    shares: 2_200_000,
    beta: 1.5,
    revenue: 0.54,
    margin: 0.18,
    backlog: 1.15,
    debtRatio: 0.22,
    quality: 0.56,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '칩렛 인터페이스 IP 테이프아웃',
    relationSeeds: [
      relation('NVX', 0.12, 'customer', 'positive', '가속기 칩렛 IP'),
      relation('HBM', 0.05, 'customer', 'positive', '패키징 검증 보드'),
      relation('SEC', -0.05, 'rival', 'negative', '보안 칩렛 IP 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.08, '달러 라이선스 매출')],
    commoditySensitivity: [commodity('cloudGpu', 0.1, 'AI 가속기 수요')],
  },
  {
    ticker: 'ORE',
    name: 'Oriole Rare Materials',
    size: 'small',
    sector: '소재',
    description: '희토류 분리와 고순도 산화물을 판매하는 미국 소재 기업',
    basePrice: 14350,
    shares: 2_500_000,
    beta: 1.34,
    revenue: 0.76,
    margin: 0.12,
    backlog: 0.98,
    debtRatio: 0.5,
    quality: 0.44,
    dividendYield: 0.003,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '희토류 분리 설비 증설',
    relationSeeds: [
      relation('KDR', 0.06, 'customer', 'positive', '방산 센서 소재'),
      relation('NVX', 0.05, 'customer', 'positive', '첨단 패키징 첨가제'),
      relation('KOB', -0.05, 'rival', 'negative', '일본 희소금속 조달 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.1, '달러 원료 판매')],
    commoditySensitivity: [commodity('rareEarth', 0.32, '희토류 가격')],
  },
  {
    ticker: 'LUM',
    name: 'Lumina Cathode',
    size: 'small',
    sector: '배터리',
    description: '저코발트 양극재와 코팅 첨가제를 개발하는 미국 배터리 소재사',
    basePrice: 26900,
    shares: 2_000_000,
    beta: 1.44,
    revenue: 0.96,
    margin: 0.1,
    backlog: 1.11,
    debtRatio: 0.57,
    quality: 0.48,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '저코발트 양극재 샘플 승인',
    relationSeeds: [
      relation('EVM', 0.09, 'customer', 'positive', '전기차 소재 샘플'),
      relation('PUR', 0.07, 'customer', 'positive', '배터리 셀 테스트'),
      relation('NAG', -0.05, 'rival', 'negative', '일본 양극재와 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.07, '달러 소재 매출')],
    commoditySensitivity: [commodity('nickel', -0.2, '양극재 원가'), commodity('lithium', -0.12, '전구체 원가')],
  },
  {
    ticker: 'ROV',
    name: 'RoveDrive',
    size: 'small',
    sector: '자동차',
    description: '자율주행 셔틀과 물류 로봇 플랫폼을 만드는 미국 모빌리티 기업',
    basePrice: 22100,
    shares: 2_300_000,
    beta: 1.42,
    revenue: 0.68,
    margin: -0.01,
    backlog: 1.05,
    debtRatio: 0.46,
    quality: 0.46,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '도심 셔틀 파일럿 운행',
    relationSeeds: [
      relation('EVM', 0.07, 'customer', 'positive', '차량 플랫폼 공유'),
      relation('SAK', -0.05, 'rival', 'negative', '로봇 택시 실증 경쟁'),
      relation('NEX', 0.06, 'supplier', 'positive', '주행 AI 모델 공급'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.06, '해외 실증 매출')],
    commoditySensitivity: [commodity('cloudGpu', -0.08, '자율주행 학습 비용')],
  },
  {
    ticker: 'SWY',
    name: 'Skyway Freight',
    size: 'small',
    sector: '자동차',
    description: '전기 밴 구독과 물류 차량 관제 서비스를 운영하는 미국 상용차 기업',
    basePrice: 12750,
    shares: 3_000_000,
    beta: 1.12,
    revenue: 0.9,
    margin: 0.06,
    backlog: 0.96,
    debtRatio: 0.64,
    quality: 0.42,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '전기 밴 리스 계약 갱신',
    relationSeeds: [
      relation('EVM', 0.08, 'supplier', 'mixed', '전기 밴 플랫폼 조달'),
      relation('BAT', 0.06, 'supplier', 'positive', '배터리 팩 서비스'),
      relation('TRS', 0.07, 'financing', 'positive', '상용차 리스 금융'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.03, '아시아 물류 고객')],
    commoditySensitivity: [commodity('oil', 0.08, '전기차 전환 경제성'), commodity('lithium', -0.08, '배터리 리스 원가')],
  },
  {
    ticker: 'NEX',
    name: 'Nexa Agents',
    size: 'small',
    sector: 'AI소프트웨어',
    description: '영업 자동화와 문서 처리 AI 에이전트를 제공하는 미국 SaaS 기업',
    basePrice: 25800,
    shares: 2_100_000,
    beta: 1.36,
    revenue: 0.72,
    margin: 0.19,
    backlog: 1.18,
    debtRatio: 0.18,
    quality: 0.57,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '영업 자동화 에이전트 출시',
    relationSeeds: [
      relation('CLD', 0.09, 'platform', 'mixed', '클라우드 마켓플레이스 수수료'),
      relation('NET', -0.05, 'rival', 'negative', 'B2B 자동화 보안 경쟁'),
      relation('NVX', 0.07, 'supplier', 'positive', '추천 모델 가속기 임대'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.06, '글로벌 구독 매출')],
    commoditySensitivity: [commodity('cloudGpu', -0.12, '추론 비용'), commodity('adSpending', 0.08, 'SaaS 수요')],
  },
  {
    ticker: 'VRS',
    name: 'VerseCloud',
    size: 'small',
    sector: 'AI소프트웨어',
    description: '실시간 3D 협업과 생성형 디자인 도구를 제공하는 미국 플랫폼사',
    basePrice: 19400,
    shares: 2_800_000,
    beta: 1.4,
    revenue: 0.64,
    margin: 0.14,
    backlog: 0.98,
    debtRatio: 0.24,
    quality: 0.5,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '3D 협업 워크스페이스 업데이트',
    relationSeeds: [
      relation('CLD', 0.08, 'platform', 'mixed', '클라우드 GPU 사용'),
      relation('STG', 0.07, 'customer', 'positive', '게임 제작 툴 채택'),
      relation('GUM', -0.04, 'rival', 'negative', 'AI 제작 도구 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.05, '글로벌 구독 매출')],
    commoditySensitivity: [commodity('cloudGpu', -0.14, '렌더링 비용'), commodity('adSpending', 0.08, '크리에이터 마케팅')],
  },
  {
    ticker: 'HEL',
    name: 'Helix Oncology',
    size: 'small',
    sector: '바이오',
    description: '유전자 편집 기반 항암 후보물질을 개발하는 미국 바이오텍',
    basePrice: 33700,
    shares: 1_500_000,
    beta: 1.62,
    revenue: 0.24,
    margin: -0.16,
    backlog: 0.54,
    debtRatio: 0.31,
    quality: 0.44,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '유전자 편집 독성시험',
    relationSeeds: [
      relation('BIOV', 0.08, 'customer', 'positive', '플랫폼 라이선스 옵션'),
      relation('MED', -0.04, 'rival', 'mixed', '진단 동반 임상 설계 경쟁'),
      relation('GEN', 0.06, 'supplier', 'positive', '유전자 전달체 공동 연구'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.04, '해외 기술이전 가치')],
    commoditySensitivity: [commodity('biotechFunding', 0.28, '고위험 임상 자금')],
  },
  {
    ticker: 'GEN',
    name: 'Genetide Bio',
    size: 'small',
    sector: '바이오',
    description: 'RNA 전달체와 희귀질환 후보물질을 연구하는 미국 플랫폼 바이오 기업',
    basePrice: 16900,
    shares: 2_200_000,
    beta: 1.5,
    revenue: 0.3,
    margin: -0.1,
    backlog: 0.6,
    debtRatio: 0.28,
    quality: 0.48,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: 'RNA 전달체 반복투여 데이터 확보',
    relationSeeds: [
      relation('HEL', 0.06, 'customer', 'positive', '유전자 전달체 공동 연구'),
      relation('BIOV', 0.05, 'customer', 'positive', '항체 병용 후보'),
      relation('ZEN', -0.04, 'rival', 'negative', '희귀질환 플랫폼 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.04, '라이선스 계약 환산')],
    commoditySensitivity: [commodity('biotechFunding', 0.24, '플랫폼 바이오 투자 심리')],
  },
  {
    ticker: 'IND',
    name: 'Indigo Defense',
    size: 'small',
    sector: '조선방산',
    description: '전자전 장비와 감시 드론을 만드는 미국 방산 기술 기업',
    basePrice: 28400,
    shares: 2_000_000,
    beta: 1.18,
    revenue: 0.86,
    margin: 0.13,
    backlog: 1.26,
    debtRatio: 0.37,
    quality: 0.54,
    dividendYield: 0.002,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '전자전 장비 실전 평가',
    relationSeeds: [
      relation('KDR', -0.05, 'rival', 'negative', '수출형 무인체계 경쟁'),
      relation('DRN', -0.05, 'rival', 'negative', '정찰 드론 입찰 경쟁'),
      relation('ORE', 0.06, 'supplier', 'mixed', '희토류 자석 소재'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.09, '달러 방산 수출')],
    commoditySensitivity: [commodity('rareEarth', -0.12, '전자전 센서 소재')],
  },
  {
    ticker: 'DOX',
    name: 'Docksafe Marine',
    size: 'small',
    sector: '조선방산',
    description: '항만 보안선과 해양 감시 시스템을 만드는 미국 해양 방산사',
    basePrice: 11950,
    shares: 2_700_000,
    beta: 1.05,
    revenue: 0.72,
    margin: 0.08,
    backlog: 1.1,
    debtRatio: 0.49,
    quality: 0.47,
    dividendYield: 0.006,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '항만 보안선 납품',
    relationSeeds: [
      relation('SEA', -0.05, 'rival', 'negative', '해양 보안선 수주 경쟁'),
      relation('MIR', 0.06, 'supplier', 'mixed', '일본 선체 설계 협력'),
      relation('STL', 0.04, 'supplier', 'mixed', '특수강 조달'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.08, '달러 수주')],
    commoditySensitivity: [commodity('steel', -0.16, '선체 소재 원가')],
  },
  {
    ticker: 'PLY',
    name: 'Playloom',
    size: 'small',
    sector: '게임콘텐츠',
    description: '인디 게임 퍼블리싱과 모드 마켓을 운영하는 미국 게임 플랫폼사',
    basePrice: 9200,
    shares: 3_600_000,
    beta: 1.32,
    revenue: 0.5,
    margin: 0.16,
    backlog: 0.82,
    debtRatio: 0.22,
    quality: 0.45,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '인디 퍼블리싱 라인업 공개',
    relationSeeds: [
      relation('STG', 0.1, 'customer', 'positive', '대형 플랫폼 퍼블리싱'),
      relation('GME', -0.04, 'rival', 'negative', '모바일 퍼블리싱 경쟁'),
      relation('KOM', -0.05, 'rival', 'negative', '콘솔 인디 IP 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.06, '글로벌 앱마켓 매출')],
    commoditySensitivity: [commodity('adSpending', 0.12, '게임 출시 마케팅')],
  },
  {
    ticker: 'AUD',
    name: 'Audion Stage',
    size: 'small',
    sector: '게임콘텐츠',
    description: '가상 공연, 음악 IP, 팬 커뮤니티를 묶은 미국 미디어 기업',
    basePrice: 15100,
    shares: 2_900_000,
    beta: 1.26,
    revenue: 0.62,
    margin: 0.17,
    backlog: 0.88,
    debtRatio: 0.27,
    quality: 0.49,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '가상 공연 티켓 판매',
    relationSeeds: [
      relation('IDP', 0.08, 'customer', 'positive', '일본 아이돌 IP 제휴'),
      relation('PIX', 0.05, 'customer', 'positive', '버추얼 아티스트 공동 공연'),
      relation('STG', 0.04, 'platform', 'mixed', '팬 커뮤니티 교차 유입'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.05, '해외 티켓 매출'), fx('USD/JPY', 0.04, '일본 팬 결제')],
    commoditySensitivity: [commodity('adSpending', 0.13, '공연 홍보 단가')],
  },
  {
    ticker: 'SOL',
    name: 'Solstice Microgrid',
    size: 'small',
    sector: '에너지',
    description: '상업용 마이크로그리드와 ESS 운영 서비스를 제공하는 미국 에너지 기업',
    basePrice: 17600,
    shares: 2_600_000,
    beta: 1.1,
    revenue: 0.82,
    margin: 0.08,
    backlog: 1.16,
    debtRatio: 0.58,
    quality: 0.5,
    dividendYield: 0.004,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '상업용 마이크로그리드 설치',
    relationSeeds: [
      relation('ARC', 0.12, 'customer', 'positive', '전력망 소프트웨어 번들'),
      relation('ESS', -0.04, 'rival', 'negative', 'ESS 시스템 입찰 경쟁'),
      relation('SUN', 0.07, 'supplier', 'positive', '태양광 모듈 조달'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.05, '해외 프로젝트 환산')],
    commoditySensitivity: [commodity('copper', -0.09, '전력 배선 원가'), commodity('lithium', -0.12, 'ESS 셀 가격')],
  },
  {
    ticker: 'URN',
    name: 'Uranium Loop',
    size: 'small',
    sector: '에너지',
    description: '원전 연료 재처리와 장기 PPA 헤지를 제공하는 미국 에너지 기업',
    basePrice: 20900,
    shares: 2_400_000,
    beta: 1.2,
    revenue: 0.78,
    margin: 0.11,
    backlog: 1.04,
    debtRatio: 0.54,
    quality: 0.48,
    dividendYield: 0.006,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '원전 연료 재처리 계약',
    relationSeeds: [
      relation('ARC', 0.06, 'customer', 'mixed', '원전 PPA 헤지'),
      relation('TOK', 0.05, 'customer', 'positive', '일본 전력 안정화 수요'),
      relation('ONS', 0.04, 'customer', 'positive', '지역 전력 계약'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.06, '달러 연료 계약')],
    commoditySensitivity: [commodity('uranium', 0.3, '원전 연료 가격'), commodity('oil', 0.04, '대체 에너지 수요')],
  },
  {
    ticker: 'TRS',
    name: 'TrustRail Finance',
    size: 'small',
    sector: '금융',
    description: '철도와 물류 인프라 리스 금융을 전문으로 하는 미국 금융사',
    basePrice: 11300,
    shares: 3_100_000,
    beta: 0.92,
    revenue: 0.84,
    margin: 0.15,
    backlog: 0.86,
    debtRatio: 0.82,
    quality: 0.46,
    dividendYield: 0.028,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '물류 인프라 리스 갱신',
    relationSeeds: [
      relation('MBB', 0.08, 'financing', 'positive', '대출 신디케이션'),
      relation('SWY', 0.07, 'customer', 'positive', '상용차 리스 금융'),
      relation('PAY', -0.04, 'rival', 'negative', '중소기업 금융 고객 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', -0.03, '외화 조달 변동')],
    commoditySensitivity: [commodity('oil', -0.06, '물류 고객 비용 부담')],
  },
  {
    ticker: 'PAY',
    name: 'Paywave Credit',
    size: 'small',
    sector: '금융',
    description: '판매자 대금 선지급과 실시간 결제를 제공하는 미국 핀테크 기업',
    basePrice: 14700,
    shares: 2_800_000,
    beta: 1.18,
    revenue: 0.7,
    margin: 0.13,
    backlog: 0.8,
    debtRatio: 0.6,
    quality: 0.44,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '판매자 선지급 한도 조정',
    relationSeeds: [
      relation('FND', -0.06, 'rival', 'negative', '소상공인 결제 경쟁'),
      relation('MBB', 0.06, 'financing', 'positive', '정산 계좌 제휴'),
      relation('TRS', -0.04, 'rival', 'negative', '중소기업 금융 고객 경쟁'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.03, '해외 판매자 정산')],
    commoditySensitivity: [commodity('adSpending', 0.06, '온라인 판매자 성장')],
  },
  {
    ticker: 'PCB',
    name: 'Pacific Carbon Materials',
    size: 'small',
    sector: '소재',
    description: '탄소복합재와 특수강 코팅을 판매하는 미국 소재 기업',
    basePrice: 16550,
    shares: 2_500_000,
    beta: 1.14,
    revenue: 0.86,
    margin: 0.1,
    backlog: 0.94,
    debtRatio: 0.48,
    quality: 0.48,
    dividendYield: 0.004,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NYSE',
    operation: '탄소복합재 항공 인증',
    relationSeeds: [
      relation('IND', 0.06, 'customer', 'positive', '방산 복합재 납품'),
      relation('STL', -0.04, 'rival', 'negative', '특수강 소재 대체 경쟁'),
      relation('SEA', 0.04, 'customer', 'mixed', '경량 선박 소재 테스트'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.06, '달러 소재 매출')],
    commoditySensitivity: [commodity('steel', -0.08, '대체 소재 가격 비교'), commodity('oil', -0.05, '탄소 섬유 원료')],
  },
  {
    ticker: 'SEC',
    name: 'SecureSilicon',
    size: 'small',
    sector: '반도체',
    description: '보안 칩렛과 하드웨어 루트오브트러스트 IP를 설계하는 미국 팹리스',
    basePrice: 23900,
    shares: 2_000_000,
    beta: 1.34,
    revenue: 0.58,
    margin: 0.21,
    backlog: 1.02,
    debtRatio: 0.18,
    quality: 0.55,
    dividendYield: 0,
    primaryCountry: 'US',
    primaryCurrency: 'USD',
    primaryExchange: 'NASDAQ',
    operation: '보안 칩렛 레퍼런스 디자인 공개',
    relationSeeds: [
      relation('CHP', -0.05, 'rival', 'negative', '칩렛 IP 경쟁'),
      relation('NVX', 0.07, 'customer', 'positive', '가속기 보안 모듈'),
      relation('KDR', 0.04, 'customer', 'positive', '방산 보안 칩 수요'),
    ],
    fxSensitivity: [fx('USD/KRW', 0.08, '달러 라이선스 매출')],
    commoditySensitivity: [commodity('cloudGpu', 0.08, '데이터센터 보안 수요')],
  },
  {
    ticker: 'YAM',
    name: 'Yamato Sensors',
    size: 'small',
    sector: '반도체',
    description: '웨이퍼 온도 센서와 차량용 라이다 수광소자를 만드는 일본 부품사',
    basePrice: 13800,
    shares: 2_600_000,
    beta: 1.18,
    revenue: 0.74,
    margin: 0.14,
    backlog: 1.08,
    debtRatio: 0.34,
    quality: 0.52,
    dividendYield: 0.006,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '웨이퍼 센서 라인 증설',
    relationSeeds: [
      relation('FJM', 0.1, 'customer', 'positive', '웨이퍼 센서 공급'),
      relation('SAK', 0.06, 'customer', 'positive', '차량용 라이다 부품'),
      relation('SEN', -0.04, 'rival', 'negative', '검사 센서 경쟁'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.08, '엔화 매출 환산'), fx('USD/JPY', 0.04, '미국 고객 수출')],
    commoditySensitivity: [commodity('memory', 0.08, '반도체 투자 수요')],
  },
  {
    ticker: 'MIZ',
    name: 'Mizuki Etch',
    size: 'small',
    sector: '반도체',
    description: '초미세 식각 장비와 세정 모듈을 공급하는 일본 반도체 장비사',
    basePrice: 28600,
    shares: 1_800_000,
    beta: 1.3,
    revenue: 0.98,
    margin: 0.19,
    backlog: 1.22,
    debtRatio: 0.36,
    quality: 0.58,
    dividendYield: 0.004,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '식각 장비 고객 검증',
    relationSeeds: [
      relation('FJM', 0.14, 'customer', 'positive', '식각 장비 납품'),
      relation('HBM', 0.06, 'customer', 'positive', '세정 모듈 테스트'),
      relation('AXI', -0.04, 'rival', 'negative', '첨단 장비 예산 경쟁'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.09, '엔화 장비 매출'), fx('USD/JPY', 0.05, '미국 수출')],
    commoditySensitivity: [commodity('memory', 0.14, '메모리 설비 투자')],
  },
  {
    ticker: 'KOB',
    name: 'Kobe Rare Materials',
    size: 'small',
    sector: '소재',
    description: '희소금속 스크랩과 세라믹 첨가제를 정제하는 일본 소재 기업',
    basePrice: 10100,
    shares: 3_000_000,
    beta: 1.12,
    revenue: 0.66,
    margin: 0.09,
    backlog: 0.94,
    debtRatio: 0.45,
    quality: 0.47,
    dividendYield: 0.007,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '희소금속 정제 수율 개선',
    relationSeeds: [
      relation('NAG', 0.12, 'supplier', 'mixed', '희소금속 조달'),
      relation('ORE', -0.05, 'rival', 'negative', '희토류 분리 경쟁'),
      relation('KDR', 0.04, 'customer', 'positive', '방산 센서 소재'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.06, '엔화 판매'), fx('USD/JPY', -0.04, '달러 원료 구매')],
    commoditySensitivity: [commodity('rareEarth', 0.26, '희소금속 가격')],
  },
  {
    ticker: 'REN',
    name: 'Ren Ceramics',
    size: 'small',
    sector: '소재',
    description: '전력반도체용 세라믹 기판과 방열 부품을 만드는 일본 소재사',
    basePrice: 15400,
    shares: 2_400_000,
    beta: 1.08,
    revenue: 0.72,
    margin: 0.13,
    backlog: 1.0,
    debtRatio: 0.32,
    quality: 0.54,
    dividendYield: 0.008,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '세라믹 기판 방열 테스트',
    relationSeeds: [
      relation('NAG', 0.08, 'customer', 'positive', '세라믹 첨가제 공급'),
      relation('DRV', 0.05, 'customer', 'positive', '전력반도체 기판'),
      relation('NAG', -0.04, 'rival', 'negative', '고방열 소재 경쟁'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.07, '엔화 매출 환산')],
    commoditySensitivity: [commodity('rareEarth', -0.08, '세라믹 첨가제 원가')],
  },
  {
    ticker: 'HIK',
    name: 'Hikari Drive',
    size: 'small',
    sector: '자동차',
    description: '하이브리드 전장 모듈과 전력 제어 부품을 공급하는 일본 부품사',
    basePrice: 19200,
    shares: 2_300_000,
    beta: 1.05,
    revenue: 0.9,
    margin: 0.1,
    backlog: 1.1,
    debtRatio: 0.42,
    quality: 0.52,
    dividendYield: 0.01,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '하이브리드 제어기 양산',
    relationSeeds: [
      relation('SAK', 0.14, 'customer', 'positive', '전장 모듈 공급'),
      relation('DRV', -0.04, 'rival', 'negative', '전기차 제어기 경쟁'),
      relation('REN', 0.06, 'supplier', 'positive', '방열 기판 조달'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.06, '엔화 매출'), fx('USD/JPY', 0.05, '미국 수출')],
    commoditySensitivity: [commodity('copper', -0.08, '전력 부품 원가')],
  },
  {
    ticker: 'RAY',
    name: 'Rayline Mobility',
    size: 'small',
    sector: '자동차',
    description: '소형 전기차 공유 플랫폼과 배터리 교환 스테이션을 운영하는 일본 기업',
    basePrice: 8600,
    shares: 3_500_000,
    beta: 1.22,
    revenue: 0.48,
    margin: 0.04,
    backlog: 0.82,
    debtRatio: 0.58,
    quality: 0.4,
    dividendYield: 0,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '배터리 교환 스테이션 확대',
    relationSeeds: [
      relation('SAK', 0.07, 'supplier', 'mixed', '소형 EV 플랫폼'),
      relation('TSC', 0.08, 'supplier', 'positive', '소형 배터리 팩'),
      relation('ROV', -0.04, 'rival', 'negative', '도심 모빌리티 실증 경쟁'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.04, '엔화 지역 매출')],
    commoditySensitivity: [commodity('lithium', -0.1, '배터리 교환 팩 원가')],
  },
  {
    ticker: 'AIM',
    name: 'Aimi Agents',
    size: 'small',
    sector: 'AI소프트웨어',
    description: '콜센터와 제조 현장용 일본어 AI 에이전트를 제공하는 소프트웨어사',
    basePrice: 23400,
    shares: 1_900_000,
    beta: 1.34,
    revenue: 0.52,
    margin: 0.18,
    backlog: 1.12,
    debtRatio: 0.16,
    quality: 0.56,
    dividendYield: 0,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '제조 현장 AI 에이전트 납품',
    relationSeeds: [
      relation('CLD', 0.06, 'platform', 'mixed', '클라우드 런타임 사용'),
      relation('GUM', -0.05, 'rival', 'negative', '아시아 기업 AI 경쟁'),
      relation('NOD', 0.05, 'supplier', 'positive', '엣지 노드 배포'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.05, '엔화 구독 매출'), fx('USD/JPY', -0.05, '달러 클라우드 비용')],
    commoditySensitivity: [commodity('cloudGpu', -0.14, '추론 비용')],
  },
  {
    ticker: 'NOD',
    name: 'NodeWave Japan',
    size: 'small',
    sector: 'AI소프트웨어',
    description: '엣지 AI 노드와 공장 데이터 수집 소프트웨어를 공급하는 일본 기업',
    basePrice: 12700,
    shares: 2_700_000,
    beta: 1.2,
    revenue: 0.58,
    margin: 0.15,
    backlog: 1.04,
    debtRatio: 0.24,
    quality: 0.5,
    dividendYield: 0,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '엣지 AI 노드 공장 설치',
    relationSeeds: [
      relation('AIM', 0.05, 'customer', 'positive', 'AI 에이전트 배포'),
      relation('FJM', 0.06, 'supplier', 'mixed', '엣지 메모리 조달'),
      relation('NET', -0.04, 'rival', 'negative', '공장 데이터 보안 경쟁'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.05, '엔화 매출')],
    commoditySensitivity: [commodity('cloudGpu', -0.08, '엣지 모델 학습 비용'), commodity('memory', -0.04, '모듈 원가')],
  },
  {
    ticker: 'ORI',
    name: 'Oribe Therapeutics',
    size: 'small',
    sector: '바이오',
    description: '오가노이드 기반 효능 평가와 신약 후보 발굴을 하는 일본 바이오텍',
    basePrice: 18450,
    shares: 1_800_000,
    beta: 1.44,
    revenue: 0.28,
    margin: -0.06,
    backlog: 0.7,
    debtRatio: 0.26,
    quality: 0.5,
    dividendYield: 0,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '오가노이드 효능 평가 확대',
    relationSeeds: [
      relation('KAI', 0.12, 'customer', 'positive', '후보물질 효능 평가'),
      relation('BIOV', 0.05, 'customer', 'positive', '항체 후보 스크리닝'),
      relation('ZEN', -0.04, 'rival', 'negative', '희귀질환 플랫폼 경쟁'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.04, '엔화 연구 매출'), fx('USD/JPY', -0.03, '미국 장비 구매')],
    commoditySensitivity: [commodity('biotechFunding', 0.18, '바이오 투자 심리')],
  },
  {
    ticker: 'ZEN',
    name: 'Zenkai Bio',
    size: 'small',
    sector: '바이오',
    description: '희귀질환 효소치료제와 세포주 개발을 하는 일본 바이오 기업',
    basePrice: 22700,
    shares: 1_600_000,
    beta: 1.48,
    revenue: 0.32,
    margin: -0.08,
    backlog: 0.68,
    debtRatio: 0.3,
    quality: 0.47,
    dividendYield: 0,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '효소치료제 전임상 데이터 확보',
    relationSeeds: [
      relation('KAI', 0.07, 'customer', 'positive', '일본 제약 공동 연구'),
      relation('GEN', -0.04, 'rival', 'negative', '희귀질환 플랫폼 경쟁'),
      relation('CRO', 0.05, 'supplier', 'mixed', '임상 생산 슬롯'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.04, '엔화 라이선스 가치')],
    commoditySensitivity: [commodity('biotechFunding', 0.22, '희귀질환 임상 자금')],
  },
  {
    ticker: 'MIR',
    name: 'Mirai Marine',
    size: 'small',
    sector: '조선방산',
    description: '해양 감시선 설계와 자율항해 모듈을 공급하는 일본 해양 기술 기업',
    basePrice: 16200,
    shares: 2_400_000,
    beta: 1.08,
    revenue: 0.62,
    margin: 0.08,
    backlog: 1.06,
    debtRatio: 0.45,
    quality: 0.48,
    dividendYield: 0.006,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '자율항해 모듈 항만 테스트',
    relationSeeds: [
      relation('DOX', 0.06, 'customer', 'mixed', '미국 보안선 설계 협력'),
      relation('CDO', -0.04, 'rival', 'negative', '해양 기자재 입찰 경쟁'),
      relation('TOK', 0.05, 'customer', 'positive', '해상풍력 유지보수선'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.05, '엔화 설계 매출'), fx('USD/JPY', 0.04, '미국 고객 수출')],
    commoditySensitivity: [commodity('steel', -0.1, '선체 설계 원가')],
  },
  {
    ticker: 'KUR',
    name: 'Kure Defense',
    size: 'small',
    sector: '조선방산',
    description: '해상 레이더와 방공 통제 소프트웨어를 개발하는 일본 방산 기업',
    basePrice: 24900,
    shares: 1_900_000,
    beta: 1.16,
    revenue: 0.74,
    margin: 0.12,
    backlog: 1.2,
    debtRatio: 0.38,
    quality: 0.53,
    dividendYield: 0.003,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '해상 레이더 소프트웨어 검증',
    relationSeeds: [
      relation('KDR', -0.06, 'rival', 'negative', '방산 전투체계 입찰 경쟁'),
      relation('YAM', 0.05, 'supplier', 'positive', '센서 부품 조달'),
      relation('SUMI', 0.04, 'financing', 'positive', '수출 금융 지원'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.05, '엔화 방산 매출'), fx('USD/JPY', 0.03, '달러 수출')],
    commoditySensitivity: [commodity('rareEarth', -0.1, '레이더 부품 소재')],
  },
  {
    ticker: 'KOM',
    name: 'Komorebi Games',
    size: 'small',
    sector: '게임콘텐츠',
    description: '콘솔 어드벤처와 애니메이션 IP 게임을 개발하는 일본 게임사',
    basePrice: 11800,
    shares: 2_900_000,
    beta: 1.22,
    revenue: 0.46,
    margin: 0.14,
    backlog: 0.82,
    debtRatio: 0.18,
    quality: 0.46,
    dividendYield: 0,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '콘솔 어드벤처 데모 공개',
    relationSeeds: [
      relation('STG', -0.04, 'rival', 'negative', '글로벌 콘솔 IP 경쟁'),
      relation('PLY', -0.05, 'rival', 'negative', '인디 퍼블리싱 계약 경쟁'),
      relation('IDP', 0.06, 'customer', 'positive', '애니메이션 IP 제휴'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.04, '엔화 매출'), fx('USD/JPY', 0.04, '해외 콘솔 판매')],
    commoditySensitivity: [commodity('adSpending', 0.12, '신작 마케팅 효율')],
  },
  {
    ticker: 'IDP',
    name: 'IdolPulse Media',
    size: 'small',
    sector: '게임콘텐츠',
    description: '버추얼 아이돌 IP와 팬 결제 플랫폼을 운영하는 일본 미디어 기업',
    basePrice: 9700,
    shares: 3_400_000,
    beta: 1.28,
    revenue: 0.5,
    margin: 0.18,
    backlog: 0.86,
    debtRatio: 0.2,
    quality: 0.48,
    dividendYield: 0,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '버추얼 콘서트 굿즈 판매',
    relationSeeds: [
      relation('PIX', 0.06, 'customer', 'positive', '버추얼 IP 공동 행사'),
      relation('AUD', 0.08, 'customer', 'positive', '가상 공연 제휴'),
      relation('KOM', 0.06, 'supplier', 'positive', '애니메이션 IP 게임화'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.05, '엔화 팬 결제'), fx('USD/JPY', 0.03, '해외 팬 결제')],
    commoditySensitivity: [commodity('adSpending', 0.14, '팬 모집 광고 단가')],
  },
  {
    ticker: 'AKR',
    name: 'Akari Solar',
    size: 'small',
    sector: '에너지',
    description: '건물 일체형 태양광과 소형 인버터를 공급하는 일본 에너지 기업',
    basePrice: 7800,
    shares: 3_800_000,
    beta: 1.06,
    revenue: 0.54,
    margin: 0.07,
    backlog: 0.98,
    debtRatio: 0.46,
    quality: 0.44,
    dividendYield: 0.005,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '건물 일체형 태양광 납품',
    relationSeeds: [
      relation('TOK', 0.06, 'customer', 'positive', '일본 전력 저장 프로젝트'),
      relation('SUN', -0.04, 'rival', 'negative', '태양광 모듈 가격 경쟁'),
      relation('ONS', 0.08, 'customer', 'positive', '지역 마이크로그리드'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.04, '엔화 매출'), fx('USD/JPY', -0.03, '달러 인버터 부품')],
    commoditySensitivity: [commodity('copper', -0.08, '인버터 원가')],
  },
  {
    ticker: 'ONS',
    name: 'Onsen Grid',
    size: 'small',
    sector: '에너지',
    description: '지역 열원과 마이크로그리드를 결합한 일본 분산 전력 기업',
    basePrice: 13400,
    shares: 2_600_000,
    beta: 0.96,
    revenue: 0.64,
    margin: 0.09,
    backlog: 1.04,
    debtRatio: 0.55,
    quality: 0.47,
    dividendYield: 0.01,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '지역 마이크로그리드 운영',
    relationSeeds: [
      relation('TOK', 0.1, 'customer', 'positive', '전력 저장 연계'),
      relation('AKR', 0.08, 'supplier', 'positive', '태양광 설비'),
      relation('URN', 0.04, 'supplier', 'mixed', '장기 전력 계약'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.04, '엔화 배당 재원')],
    commoditySensitivity: [commodity('lng', -0.1, '지역 열원 연료비'), commodity('copper', -0.05, '배전 설비 원가')],
  },
  {
    ticker: 'SHN',
    name: 'Shinsei Lease',
    size: 'small',
    sector: '금융',
    description: '공장 자동화 설비와 상용차 리스를 제공하는 일본 금융사',
    basePrice: 9200,
    shares: 3_200_000,
    beta: 0.88,
    revenue: 0.76,
    margin: 0.13,
    backlog: 0.86,
    debtRatio: 0.78,
    quality: 0.46,
    dividendYield: 0.026,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '공장 설비 리스 포트폴리오 관리',
    relationSeeds: [
      relation('SUMI', 0.12, 'platform', 'positive', '리스 포트폴리오 공동 판매'),
      relation('SAK', 0.05, 'customer', 'positive', '상용차 리스'),
      relation('KYO', -0.04, 'rival', 'negative', '지역 기업 대출 경쟁'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.04, '엔화 배당 환산'), fx('USD/JPY', -0.03, '달러 조달 비용')],
    commoditySensitivity: [commodity('steel', -0.04, '설비 투자 비용')],
  },
  {
    ticker: 'KYO',
    name: 'Kyoto Capital',
    size: 'small',
    sector: '금융',
    description: '지역 벤처대출과 상장 준비 컨설팅을 하는 일본 금융 부티크',
    basePrice: 7200,
    shares: 3_700_000,
    beta: 1.02,
    revenue: 0.42,
    margin: 0.14,
    backlog: 0.78,
    debtRatio: 0.52,
    quality: 0.43,
    dividendYield: 0.012,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '벤처대출 심사 강화',
    relationSeeds: [
      relation('SUMI', 0.05, 'financing', 'positive', '공동 대출 신디케이션'),
      relation('AIM', 0.06, 'customer', 'positive', 'AI 스타트업 금융'),
      relation('SHN', -0.04, 'rival', 'negative', '지역 기업 금융 경쟁'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.04, '엔화 수익 환산')],
    commoditySensitivity: [commodity('biotechFunding', 0.06, '벤처 투자 심리')],
  },
  {
    ticker: 'TSC',
    name: 'Tsukuba Cell',
    size: 'small',
    sector: '배터리',
    description: '소형 전고체 셀과 전동화 부품용 배터리 팩을 개발하는 일본 기업',
    basePrice: 25800,
    shares: 1_900_000,
    beta: 1.46,
    revenue: 0.48,
    margin: 0.02,
    backlog: 1.12,
    debtRatio: 0.5,
    quality: 0.45,
    dividendYield: 0,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Growth',
    operation: '소형 전고체 셀 파일럿 생산',
    relationSeeds: [
      relation('SAK', 0.08, 'customer', 'positive', '소형 EV 샘플'),
      relation('RAY', 0.08, 'customer', 'positive', '배터리 교환 팩'),
      relation('BAT', -0.05, 'rival', 'negative', '팩 모듈 가격 경쟁'),
      relation('NAG', 0.08, 'supplier', 'mixed', '양극재 소재'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.05, '엔화 매출'), fx('USD/JPY', -0.04, '달러 소재 조달')],
    commoditySensitivity: [commodity('lithium', -0.16, '셀 소재 원가'), commodity('nickel', -0.08, '양극재 원가')],
  },
  {
    ticker: 'NIR',
    name: 'Niren Recycle',
    size: 'small',
    sector: '소재',
    description: '폐전자제품과 배터리 스크랩에서 금속을 회수하는 일본 재활용 기업',
    basePrice: 11200,
    shares: 2_900_000,
    beta: 1.18,
    revenue: 0.6,
    margin: 0.09,
    backlog: 0.92,
    debtRatio: 0.43,
    quality: 0.45,
    dividendYield: 0.004,
    primaryCountry: 'JP',
    primaryCurrency: 'JPY',
    primaryExchange: 'TSE Standard',
    operation: '배터리 스크랩 회수 계약',
    relationSeeds: [
      relation('RCY', -0.04, 'rival', 'negative', '재활용 원료 입찰 경쟁'),
      relation('NAG', 0.06, 'customer', 'positive', '재활용 금속 공급'),
      relation('TSC', 0.05, 'customer', 'positive', '소형 셀 회수 계약'),
    ],
    fxSensitivity: [fx('JPY/KRW', 0.04, '엔화 금속 매출'), fx('USD/JPY', 0.03, '달러 금속 가격')],
    commoditySensitivity: [commodity('nickel', 0.18, '회수 금속 가격'), commodity('lithium', 0.14, '리튬 재활용 가치')],
  },
] satisfies CompanyBlueprint[]

export const LARGE_COMPANY_BLUEPRINTS = largeCompanyBlueprints
export const SMALL_COMPANY_BLUEPRINTS = smallCompanyBlueprints
export const COMPANY_BLUEPRINTS = [...largeCompanyBlueprints, ...smallCompanyBlueprints] satisfies CompanyBlueprint[]

export const COMPANY_UNIVERSE_COUNTS = {
  large: largeCompanyBlueprints.length,
  small: smallCompanyBlueprints.length,
  total: largeCompanyBlueprints.length + smallCompanyBlueprints.length,
} as const

export function createCompanyUniverse(): Company[] {
  return COMPANY_BLUEPRINTS.map(toMarketCompany)
}

export function toMarketCompany(blueprint: CompanyBlueprint): Company {
  return {
    ticker: blueprint.ticker,
    name: blueprint.name,
    exchange: marketExchangeFor(blueprint.primaryExchange),
    country: blueprint.primaryCountry,
    currency: blueprint.primaryCurrency,
    size: blueprint.size,
    sector: blueprint.sector,
    tags: blueprint.tags ?? defaultTagsFor(blueprint),
    description: blueprint.description,
    price: blueprint.basePrice,
    prevClose: blueprint.basePrice,
    open: blueprint.basePrice,
    fairPrice: fairPriceFor(blueprint),
    shares: blueprint.shares,
    beta: blueprint.beta,
    revenue: blueprint.revenue,
    margin: blueprint.margin,
    backlog: blueprint.backlog,
    debtRatio: blueprint.debtRatio,
    quality: blueprint.quality,
    sentiment: blueprint.sentiment ?? 0,
    dividendYield: blueprint.dividendYield,
    relations: blueprint.relationSeeds.map(toMarketRelation),
    history: [blueprint.basePrice],
    lastReturn: 0,
    dayVolume: 0,
    status: blueprint.status ?? '정상',
    operation: blueprint.operation,
    distress: initialDistressFor(blueprint),
    badStreak: 0,
    auditFlag: blueprint.margin < -0.12 || blueprint.debtRatio > 0.9 ? 1 : 0,
    alive: true,
    listedDay: 1,
    commoditySensitivity: marketCommoditySensitivityFor(blueprint),
  }
}

export const COMPANY_UNIVERSE = createCompanyUniverse()

function toMarketRelation(seed: RelationSeed): Relation {
  return {
    ticker: seed.ticker,
    weight: seed.weight,
    reason: seed.reason,
  }
}

function marketExchangeFor(primaryExchange: PrimaryExchange): Exchange {
  switch (primaryExchange) {
    case 'TSE Prime':
    case 'TSE Standard':
      return 'TSE'
    case 'TSE Growth':
      return 'MOTHERS'
    default:
      return primaryExchange
  }
}

function defaultTagsFor(blueprint: CompanyBlueprint): string[] {
  const tags = new Set<string>([blueprint.size, blueprint.primaryCountry.toLowerCase(), blueprint.sector])

  switch (blueprint.sector) {
    case '반도체':
      tags.add('semiconductor')
      if (blueprint.ticker === 'HBM' || blueprint.ticker === 'FJM' || blueprint.description.includes('HBM')) tags.add('hbm')
      if (blueprint.description.includes('장비') || ['SEN', 'AXI', 'MIZ', 'YAM'].includes(blueprint.ticker)) tags.add('semicap')
      break
    case '소재':
      tags.add('materials')
      if (blueprint.description.includes('배터리') || hasCommodity(blueprint, ['lithium', 'nickel', 'rareEarth'])) tags.add('battery-material')
      break
    case '자동차':
      tags.add('mobility')
      if (blueprint.description.includes('전기') || blueprint.description.includes('EV') || blueprint.description.includes('electric')) tags.add('ev')
      break
    case 'AI소프트웨어':
      tags.add('ai')
      tags.add('cloud')
      tags.add('ai-server')
      break
    case '바이오':
      tags.add('bio')
      break
    case '배터리':
      tags.add('battery')
      break
    case '조선방산':
      tags.add('ship')
      tags.add('defense')
      break
    case '게임콘텐츠':
      tags.add('game')
      tags.add('content')
      break
    case '에너지':
      tags.add('energy')
      break
    case '금융':
      tags.add('finance')
      break
    case '보안':
      tags.add('security')
      break
    case '클라우드':
      tags.add('cloud')
      break
    case '로봇':
      tags.add('robotics')
      break
    case '우주항공':
      tags.add('aerospace')
      break
    case '물류':
      tags.add('logistics')
      break
    case '유통소비':
      tags.add('consumer')
      break
    case '미디어':
      tags.add('media')
      break
    case '음식료':
      tags.add('food')
      break
  }

  return [...tags]
}

function fairPriceFor(blueprint: CompanyBlueprint) {
  const edge = (blueprint.quality - 0.5) * 0.18 + blueprint.margin * 0.22 + (blueprint.backlog - 1) * 0.04 - blueprint.debtRatio * 0.035
  const fairPrice = blueprint.basePrice * (1 + edge)
  return blueprint.primaryCurrency === 'USD' ? Number(fairPrice.toFixed(2)) : Math.round(fairPrice)
}

function initialDistressFor(blueprint: CompanyBlueprint) {
  return Math.max(0, Math.min(4, Math.round((blueprint.debtRatio - 0.72) * 4 + (blueprint.margin < 0 ? 1.4 : 0))))
}

function marketCommoditySensitivityFor(blueprint: CompanyBlueprint): MarketCommoditySensitivity {
  const sensitivity: MarketCommoditySensitivity = {}

  for (const item of blueprint.fxSensitivity) {
    if (item.pair.includes('USD')) addMarketSensitivity(sensitivity, 'dollar', item.weight)
    if (item.pair.includes('JPY')) addMarketSensitivity(sensitivity, 'yen', item.weight)
  }

  for (const item of blueprint.commoditySensitivity) {
    switch (item.commodity) {
      case 'memory':
        addMarketSensitivity(sensitivity, 'memory', item.weight)
        break
      case 'cloudGpu':
        addMarketSensitivity(sensitivity, 'memory', item.weight * 0.7)
        break
      case 'lithium':
        addMarketSensitivity(sensitivity, 'lithium', item.weight)
        break
      case 'nickel':
        addMarketSensitivity(sensitivity, 'lithium', item.weight * 0.6)
        break
      case 'oil':
        addMarketSensitivity(sensitivity, 'oil', item.weight)
        break
      case 'lng':
        addMarketSensitivity(sensitivity, 'oil', item.weight * 0.6)
        break
      case 'uranium':
        addMarketSensitivity(sensitivity, 'oil', item.weight * 0.35)
        break
      case 'steel':
      case 'copper':
        addMarketSensitivity(sensitivity, 'freight', item.weight)
        break
      case 'rareEarth':
        addMarketSensitivity(sensitivity, 'freight', item.weight * 0.5)
        break
      case 'biotechFunding':
      case 'adSpending':
        break
    }
  }

  return sensitivity
}

function addMarketSensitivity(target: MarketCommoditySensitivity, key: keyof MarketCommoditySensitivity, weight: number) {
  target[key] = Number(((target[key] ?? 0) + weight).toFixed(3))
}

function hasCommodity(blueprint: CompanyBlueprint, commodities: Commodity[]) {
  return blueprint.commoditySensitivity.some((item) => commodities.includes(item.commodity))
}
